### PR TITLE
Fix for test/unit/sql/data-types.test.js

### PR DESCRIPTION
**Pull request by kulkarnih**
The data-types.test.js reports a type error for absence of `warn` function.

`TypeError: Object object has no method 'warn'`

Added the definition for the warn function based on the definition in other [dialects](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/data-types.js#L6).

### CODE REVIEW

**Comment by kulkarnih** [comment]
This is not related to the current PR.

What is the `dateToString` in `lib/sql-string.js` supposed to do? It is not defined and shows errors in the tests.

**Comment by gintsgints** [comment]
May be better next time create new issue for discussing different topic.

To answer I searched history of code and found that function look like this:

```
SqlString.dateToString = function(date, timeZone, dialect) {
  var dt = new Date(date);

  // TODO: Ideally all dialects would work a bit more like this
  if (dialect === "postgres") {
    return moment(dt).zone('+00:00').format("YYYY-MM-DD HH:mm:ss.SSS Z");
  }

  if (timeZone !== 'local') {
    var tz = convertTimezone(timeZone);

    dt.setTime(dt.getTime() + (dt.getTimezoneOffset() * 60000));
    if (tz !== false) {
      dt.setTime(dt.getTime() + (tz * 60000));
    }
  }

  return moment(dt).format("YYYY-MM-DD HH:mm:ss");
};
```

**Comment by kulkarnih** [comment]
You have not enabled "Issue management" for your repo. Which is why I asked you in the sequelize/sequelize project, if there is a better way to contact. :)

If you enable issue management, we can start a discussion there.

**Comment by gintsgints** [comment]
Thank you for letting me know. Enabled now!

**Pull request merged**
